import { test, expect } from '@playwright/test';
test('computer dashboard streams tasks, decisions, models and pairing QR', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await page.locator('#token').fill('test-only-token-0123456789abcdefgh');
  await page.getByRole('button', { name: '进入控制室 ↗' }).click();
  await expect(page.locator('#connection')).toHaveText('● 已连接');
  await page.locator('#agent').selectOption('codex');
  await page.getByRole('button', { name: '＋ 新建会话' }).click();
  await expect(page.locator('#model')).toHaveValue('test/model-a');
  await page.locator('#model').selectOption('test/model-b');
  await expect(page.locator('#model')).toHaveValue('test/model-b');
  await page.locator('#prompt').fill('电脑端任务验证'); await page.locator('#send').click();
  await expect(page.locator('.thinking')).toContainText('正在分析局域网任务');
  await expect(page.locator('#plan')).toContainText('等待授权');
  await expect(page.locator('.tool')).toContainText('读取完成');
  await expect(page.locator('.choice')).toContainText('选择执行方式');
  await page.screenshot({ path: '../artifacts/desktop-running.png', fullPage: true });
  await page.locator('.choice').getByRole('button', { name: '继续', exact: true }).click();
  await expect(page.locator('#timeline')).toContainText('任务 completed');
  await page.reload(); await expect(page.locator('#connection')).toHaveText('● 已连接');
  await page.locator('.session').last().click(); await expect(page.locator('#timeline')).toContainText('选择结果：继续');
  await page.getByRole('button', { name: '手机配对' }).click();
  await expect(page.locator('#pairDialog')).toBeVisible();
  await expect(page.locator('#qr')).toHaveAttribute('src', /^data:image\/png/);
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await page.screenshot({ path: '../artifacts/desktop-completed.png', fullPage: true });
  page.once('dialog', d => d.accept());
  await page.getByRole('button', { name: '关闭会话', exact: true }).click();
  await expect(page.locator('#status')).toContainText('offline');
  expect(errors).toEqual([]);
});
test('launcher fragment authenticates without leaking token into HTTP URLs', async ({ page }) => {
  const requests = []; page.on('request', r => requests.push(r.url()));
  await page.goto('/#token=test-only-token-0123456789abcdefgh');
  await expect(page.locator('#connection')).toHaveText('● 已连接');
  expect(new URL(page.url()).hash).toBe('');
  expect(requests.every(url => !url.includes('test-only-token'))).toBe(true);
});
